### ISSUE TITLE
How to make auto play on Mobile

### ISSUE THREAD

**Issue by vikas1981** [spark-mv/spark_player#27]
I tried to set the "enable_autoplay_on_mobile" but still it doesn't auto play on mobile.

Can i have some  working sample which is auto play on Android & iOS mobile devices ?

**Comment by akashta** [comment]
Auto play on mobile is not always allowed. You can try to initialize the player with `mute: true` option.
Here is auto play policies for iOS: https://webkit.org/blog/6784/new-video-policies-for-ios/
And Android: https://developers.google.com/web/updates/2016/07/autoplay

**Comment by vikas1981** [comment]
Akashta,

Thanks for the help. I am able to auto play video on iOS.
But video play, sound icon just disappear and there is no way to enable sound by user interaction.

There is another problem i see, once i click on video, it is supposed to generate a click but it paused the video and i see exception in console:

ima3.js:685 Uncaught TypeError: Cannot read property 'apply' of undefined
    at uo (ima3.js:685)
    at so.N (ima3.js:686)
    at sf (ima3.js:466)
    at P (ima3.js:464)
    at eo.C (ima3.js:676)
    at pf (ima3.js:462)
    at mf (ima3.js:463)
    at ima3.js:460

**Comment by akashta** [comment]
Could you please provide an example (e.g. link to the test page or jsbin)?

**Comment by vikas1981** [comment]
Akasta,

Here is the sample:

> 
> <html>
> <head>
>     <script src="hola_player.dev.js"></script>
> </head>
> <body>
>   <div><h1>Video tag with Hola player - playing MP4 with ads</h1></div>
>   <video preload="none" autoplay muted playsinline class="video-js vjs-default-skin"
>     width="640" height="360" controls>
>     <source
>       src="blank.mp4"
>       type="video/mp4" label="1080p">
>   </video>
>   <script>
>     (function(){
>       var doc='<VAST version="2.0"><Ad id="601364"><InLine><AdSystem>Acudeo Compatible</AdSystem><AdTitle>VAST 2.0 Instream Test 1</AdTitle><Description>VAST 2.0 Instream Test 1</Description><Creatives><Creative AdID="601364"><Linear><Duration>00:00:30</Duration><TrackingEvents></TrackingEvents><VideoClicks><ClickThrough>https://google.com</ClickThrough></VideoClicks><MediaFiles><MediaFile delivery="progressive" type="video/mp4" bitrate="500" width="400" height="300" scalable="true" maintainAspectRatio="true">http://techslides.com/demos/sample-videos/small.mp4</MediaFile></MediaFiles></Linear></Creative><Creative AdID="601364-Companion"></Creative></Creatives></InLine></Ad></VAST>';
>       
>       window.hola_player({
>       	enable_autoplay_on_mobile: true,
>         ads: {
>         	adsResponse: doc,
>         },
>         settings: {
> 			quality: true,
> 		},
>       });
>     })();
>   </script>
> </body>
> </html>
>

**Comment by akashta** [comment]
there is no `muted` option шт in your sample.
Here is the working example: http://jsbin.com/jutaxaboje/edit?html,output

**Comment by vikas1981** [comment]
Akashta,

Thanks for the response. I have added the option for muted in my sample and still click on video doesn't work. 

http://avng-sp-q1media.s3.amazonaws.com/vslider/sample.html


Ot still errors out

Uncaught TypeError: Cannot read property 'apply' of undefined
    at Wp (ima3.js:320)
    at Up.O (ima3.js:321)
    at Mf (ima3.js:83)
    at Q (ima3.js:81)
    at Gp.C (ima3.js:311)
    at Jf (ima3.js:79)
    at Gf (ima3.js:80)
    at ima3.js:77

**Comment by akashta** [comment]
your page works for me. It's possible that player saved volume and tries to restore it when video starts.
You can try to check it in a private mode to avoid this.

**Comment by vikas1981** [comment]
Akashta,

The click on video doesn't open landing page. The volume just works fine for me too.

Can you please click on video and it should open click URL in browser but it throws exception ?

**Comment by akashta** [comment]
To open url on mobile you have to click on "Learn More" link. Click on the video itself just pauses it.
