### ISSUE TITLE
skippable preroll ads on ios

### ISSUE THREAD

**Issue by tonykor** [spark-mv/spark_player#35]
Hello, as far as i found preroll ads not playing in the player.

**Comment by akashta** [comment]
Hi, the following example works fine for me: http://hola.github.io/examples/cdn/#hola_player_ima

**Comment by tonykor** [comment]
It's non-skipable preroll,  do you test skipable preroll videos?

**Comment by akashta** [comment]
could you please check on this example?
http://output.jsbin.com/fosozeviyi

**Comment by tonykor** [comment]
I confirm that there is no preroll video ad on the example provided.

**Comment by akashta** [comment]
skippable ads are not supported on ios.

http://googleadsdeveloper.blogspot.ru/2017/06/new-custom-playback-apis-for-ima-html5.html

Enabling skippable ads with `google.ima.settings.setDisableCustomPlaybackForIOS10Plus(true)` will break fullscreen implementation.

**Comment by tonykor** [comment]
Hello,

does anything changed since that time or skipable prerolls are still not supported in iOS ?

**Comment by akashta** [comment]
The latest spark player version supports skippable ads on iOS. This feature disabled by default. To activate it need to init the player with the following param
```
ads: {
    disableCustomPlaybackForIOS10Plus: true
 }
```
Playing ads (any ads, not just skippable) in fullscreen mode is not supported when this param is enabled, so fullscreen button will be hidden when ad is playing.

**Comment by tonykor** [comment]
it works, thanks!
