### ISSUE TITLE
Custom HLS quality level labels

### ISSUE THREAD

**Issue by awakenedguy** [spark-mv/spark_player#38]
Hi,

How could I specify a custom labels for HLS quality levels, like "360p", "720p" etc, in free self-hosted player? By default it just shows autodetected bitrates.

Thanks.

**Comment by akashta** [comment]
Hi,
You need to specify resolution param in the hls playlist.
e.g.: `RESOLUTION=1280x720`
http://player.h-cdn.org/static/hls/cdn2/master.m3u8

**Comment by awakenedguy** [comment]
Ah, so the reason why it did not work for me, was probably because the player only recognizes some predefined set of standard resolutions. I have plenty of videos with non-standard resolutions where either X or Y slightly deviates from standard values.

Like e.g.:

RESOLUTION=640x346
RESOLUTION=854x462 
RESOLUTION=1280x694
RESOLUTION=1920x1040

Precise resolutions of all of those videos are specified in the HLS master playlist exactly that way, but the Hola player then doesn't recognize them as 360p, 480p, 720p and 1080p respectively. In other players, like e.g. in flowplayer, there is a simple and documented way to specify a custom label right in html/js. Is there a way to do a thing like that in Hola player?

**Comment by akashta** [comment]
There is no documented way to override quality labels.
But you can workaround it by adding custom translation:
```
var res_map = {
    '346p': '360p',
    '462p': '480p',
    '694p': '720p',
    '1040p': '1080p',
};
window.hola_player({force_language: 'en', videojs_options: {languages: {en: res_map}}});
```
