### ISSUE TITLE
how responsive hola in mobile 

### ISSUE THREAD

**Issue by sajadzangene** [spark-mv/spark_player#45]
Hi. How I responsive hola video in mobile? 

window.hola_player({videojs_options: {fluid: true}});

where should I add this code?
how should I make it width 100%?
thanks

**Comment by akashta** [comment]
Hi, here is an example
https://jsfiddle.net/b23Lpeaw/

**Comment by sajadzangene** [comment]
thanks, but not work for me.
my web: http://mag.ebayfarsi.com/ebayfarsi-affiliate-guide/

**Comment by akashta** [comment]
another option is to enable it on holaspark configuration panel:
Configuration -> Hola Player -> Appearance -> Size -> Responsive 16:9

**Comment by ERI123** [comment]
<video class="video-js vjs-default-skin vjs-16-9"
add vjs-16-9 and will do the work
