### ISSUE TITLE
How to play multiple different preload ads, Before the video is played?

### ISSUE THREAD

**Issue by ouedward** [spark-mv/spark_player#50]
Dear Sir,
  My website use the Hola Player Without installing extension, add the code to the site FUNTION!
How to play multiple different preload ads, Before the video is played?

**Comment by akashta** [comment]
Hi, @ouedward 
Here is an example of ads scheduling. You can add multiple pre-roll ads with `time: 'start'`:
http://hola.github.io/examples/cdn/#spark_player_ads_schedule
