### ISSUE TITLE
Hls.js is not supported in this browser

### ISSUE THREAD

**Issue by aaronnoa2** [spark-mv/spark_player#53]
Im trying to implement the Video player on a website which is gonna be shown on a smart Tv.
When trying to plat the video the following  error shows up (Hls.js is not supported in this browser!).

This is the user agent:
(Mozilla/5.0 (Linux; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 SRAF/3.5 HbbTV/1.2.1 (; Sharp_UMC; BLA-43; V1.00; V1.0; 2015); CE-HTML/1.0 FXM-U2FsdGVkX181oE6S3GnSi3AL7uBqsplcp3Y1l4r+La5UNjUqj3KjowAR6Fi9818b-END).

Then I got the following error from VideoJS:
(VIDEOJS:ERROR:(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)The media could not be loaded, either because the server or network failed or because the format is not supported.
-[Object]
+[Prototype]
code: 4
message: The media could not be loaded, either because the server or network failed or because the format is not supported.).

Actually the tv browser does support m3u8 video format, and im almost sure that if i am able to 'disable' the Hls.js file these error would be solved but I don't know how.

edit: I forgot that I am adding the url and the xml format trough the Spark web page and not adding a plugin.

Thanks in advance.

**Comment by akashta** [comment]
hls.js should not interfere with other methods. Player tries to play a video using various methods and if nothing helps it shows this error message.
