### ISSUE TITLE
How to update to the newest videojs version?

### ISSUE THREAD

**Issue by timokuehne** [spark-mv/spark_player#55]
We use your player as the self-hosted solution. Is it possible updating the hola_player.js to the newest version of videojs (7.0.4)? If yes, how?

**Comment by akashta** [comment]
It is not possible. We use forked version of videojs which contains a lot of improvements. So the player won't work with the regular videojs.

**Comment by timokuehne** [comment]
Okay. We will develop spark player and bring it together with the current version of videojs. Thanks for your answer.
