### ISSUE TITLE
HLS.js error: mediaError - fatal: false - bufferStalledError

### ISSUE THREAD

**Issue by timokuehne** [spark-mv/spark_player#57]
I tried spark player with hls. I was wondering, because loading and seeking is very slow, but it should be very fast with hls. If I seek the video, then I get the following warning message. Look in the attached file. The same error I get in your HLS example. I think this error makes seeking very slow.
![hls-error](https://user-images.githubusercontent.com/11676348/41839953-d59181d2-7864-11e8-9f4f-e072d700d3e4.png)

**Comment by akashta** [comment]
Hi @timokuehne 
I checked this video and the seek takes about 1-2sec for me. This warning message is not an actual error, it just indicates that the video buffer is empty
