### ISSUE TITLE
Play Pre- roll and overlay Ads

### ISSUE THREAD

**Issue by nvd095** [spark-mv/spark_player#59]
Hi Team,
                  We are trying to implement HOLA Player where the scenario is as below
 
1.	Pre-Roll Ad plays first.
2.	Followed by an overlay ad banner .

Below are the few implementations:

 ads: {
          adTagUrl: tags['linear']||p,
          adTagUrl: tags['non_linear']||p,
          
        },

---------------------------------------------------------------

 ads: {
          adTagUrl: tags[p||'linear']||p,
          
        },
         ads: {
          adTagUrl: tags[p||'non_linear']||p,
          
        },

It just plays the last ad .. Please help us resolve the issue .

**Comment by mahmutbayri** [comment]
You can use VMAP using  `adsResponse` option of `ads` options instead of `adTagUrl`. 

```
ads: {
      adsResponse: vmapXmlContent,
    },
```

Some vmap examples is here https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags?hl=tr

**Comment by akashta** [comment]
Hi, @nvd095 
ads.schedule param has been added in Spark Player v1.0.157.
Here is an example with linear pre-roll, overlay ad and linear post-roll: 
http://hola.github.io/examples/cdn/#spark_player_ads_schedule
